[package]
edition = "2021"
name = "cache"
version = "0.1.0"

[dependencies]
env_logger = "0.9.0"
log = "0.4.17"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.83"
lazy_static = "1.4.0"
time = "0.3.11"
